config/routes.rb
InitialRelease::Application.routes.draw do  
  
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :password_resets
  resources :sessions

  get 'wellcom' => 'home#wellcom'
  get 'set_city' => 'home#set_city', as: 'set_city'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  match '', to: 'cities#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  
  root :to =>  "cities#index", :requirements => { :subdomain => "voronezh" } #"cities#index"

  defaults :subdomain => false do
    root :to => 'cities#index'
  end

  resources :prices
  resources :promotions do
    post :search, on: :collection
    get :start    
  end

  resources :photo_prices
  resources :chains
  resources :products
  resources :discussions do
    member do
      get 'change_visible'
    end
  end

  resources :cities do
    get :set_shops_prices
    get :update_shop_raiting
    resources :shops
    resources :xml_files
    resource :shop_products
    resources :areas do
      resources :chains do 
        resources :shops
      end
    end
  end

  resources :areas do
    resources :shops
  end

  resources :users do
    resources :roles
    resources :xml_files
    member do
      get :activate
    end
    collection do 
      post :sign_with_social
    end
  end

  

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  #establish_connection "production"
  acts_as_tree
  
  belongs_to :user  
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  before_filter :check_admin, only: [:change_visible]

  def index
    if current_user && current_user.admin?
      @discussions = Discussion.roots
    else
      @discussions = Discussion.roots.where(visible: true)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discussions }
    end
  end

  def change_visible
    @discussion = Discussion.find(params[:id])
    @discussion.update_attributes(visible: (!@discussion.visible))
    redirect_to discussions_url
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @discussion }
    end
  end

  # GET /discussions/new
  # GET /discussions/new.json
  def new
    @discussion = Discussion.new(parent_id: params[:parent_id])
  end

  # GET /discussions/1/edit
  def edit
    @discussion = Discussion.find(params[:id])
  end

  # POST /discussions
  # POST /discussions.json
  def create
    params[:discussion][:user_id] = current_user.id if current_user
    @discussion = Discussion.new(params[:discussion])
    @discussion.save
    respond_to do |format|
      format.js { render 'create' } 
      format.html { redirect_to discussions_url }
    end
  end

  # PUT /discussions/1
  # PUT /discussions/1.json
  def update
    @discussion = Discussion.find(params[:id])

    respond_to do |format|
      if @discussion.update_attributes(params[:discussion])
        format.html { redirect_to @discussion, notice: 'Discussion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    Discussion.find(params[:id]).destroy if current_user && current_user.admin? #(current_user.admin? || Discussion.find(params[:id]).user == current_user)
    redirect_to discussions_url
  end

  private
  def check_admin
    if !current_user || !current_user.admin?
      redirect_to :root
    end
  end
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/discussions/_answer.html.haml
= form_for @discussion, html: {class:'form-horizontal', style: 'margin:20px'} do |f|
  = hidden_field_tag 'discussion[parent_id]', @discussion.parent_id
  = f.text_area :body, style: "width:500px;height:80px;", placeholder: "Текст комментария ...", row: 6
  = f.submit 'опубликовать', class: "btn btn-large btn-info", style: 'text-align:center;width:300px;margin:8px auto;display:block'

app/views/discussions/_discussion.html.haml
%blockquote.offset1.span10{style: 'margin-top:10px'}
  %p= discussion.body
  =# link_to "#{discussion.visible != true ? 'отобразить' : 'скрыть'}", change_visible_discussion_path(discussion), class: 'btn' if current_user && current_user.admin?
  = link_to 'редактировать', edit_discussion_path(discussion), class: 'btn btn-success' if current_user && current_user.admin?
  = link_to 'удалить', discussion, class: 'btn btn-danger', :confirm => 'Вы уверены?', :method => :delete if (current_user && (current_user.admin? || (discussion.user && discussion.user == current_user)))

app/views/discussions/_form.html.haml
= form_for @discussion do |f|
  -if @discussion.errors.any?
    #error_explanation
      %h2= "#{pluralize(@discussion.errors.count, "error")} prohibited this discussion from being saved:"
      %ul
        - @discussion.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :parent_id
    = f.number_field :parent_id
  .field
    = f.label :visible
    = f.check_box :visible
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :user_name
    = f.text_field :user_name
  .actions
    = f.submit 'Save'

app/views/discussions/create.js.erb
$('.modal').html("<div class='modal-header'><button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button><h3>Спасибо</h3></div><div class='modal-body'><p>Благодарим Вас за проявленный интерес к сайту. В самое ближайшее время наш сотрудник ответи на вопрос, после чего Вы сможете найти сам вопрос и ответ на данной странице.</p></div>");
$('.modal').modal();
$('#inputTitle').val('');
$('#inputBody').val('');
$('#collapseOne').collapse('hide');

app/views/discussions/edit.html.haml
%h1 Editing discussion

= render 'form'

= link_to 'Show', @discussion
\|
= link_to 'Back', discussions_path

app/views/discussions/index.html.haml
:javascript
  $(document).ready(function() { 
    $('form#new_discussion').submit(function(){
      if ( $('form #inputTitle').val() == '' || $('form #inputName').val() == '' || $('form #inputBody').val() == '' )
      {
        alert('все поля должны быть заполнены!');
        return false;
      }
    });
  });
%legend Вопросы, ответы, обсуждения
.accordion#accordion1
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{'data-toggle' => "collapse", 'data-parent' => "#accordion1", href: "#collapseOne"} Задать вопрос
    #collapseOne.accordion-body.collapse
      .accordion-inner        
        = form_for Discussion.new, html: {class:'form-horizontal', style: 'margin-bottom:0'}, remote: true do |f|
          = f.hidden_field :parent_id
          .control-group{style: 'margin-bottom:2px'}
            %label.control-label{:for => "inputTitle"} Заголовок
            .controls
              = f.text_field :title, id:'inputTitle', placeholder:"Заголовок", class: 'span10'
          .control-group{style: 'margin-bottom:2px'}
            %label.control-label{:for => "inputName"} Ваше имя
            .controls
              = f.text_field :user_name, id:'inputName', placeholder:"Ваше имя", class: 'span10'
          .control-group{style: 'margin-bottom:2px'}
            %label.control-label{:for => "inputBody"} Сообщение
            .controls
              = f.text_area :body, class: "span10", placeholder: "Текст сообщения ...", rows: "5", id:'inputBody'
          = f.submit 'опубликовать', class: "btn btn-large btn-info", style: 'text-align:center;width:300px;margin:8px auto;display:block'
.clearfix
.accordion#accordion2
  .accordion-group
    - @discussions.each_with_index do |discussion, index|
      .accordion-heading
        %a.accordion-toggle{'data-toggle' => "collapse", 'data-parent' => "#accordion2", href: "#collapse#{discussion.id.to_s}", style: 'width:300px;display:inline-block'}= discussion.title
        - if current_user && current_user.admin? #|| (discussion.user && discussion.user == current_user)))
          = link_to discussion, class: 'btn btn-danger pull-right', style: 'width:20px;border-radius:0', :confirm => 'Вы уверены?', :method => :delete do
            %i.icon-trash.icon-white
        - if current_user && current_user.admin?
          = link_to edit_discussion_path(discussion), class: 'btn btn-success pull-right', style: 'width:20px;border-radius:0' do
            %i.icon-edit.icon-white
        - if current_user && current_user.admin?
          = link_to change_visible_discussion_path(discussion), class: 'btn pull-right', style: 'width:20px;border-radius:0' do
            - if discussion.visible == true
              %i.icon-eye-open
            - else
              %i.icon-eye-close
        - if current_user && current_user.admin?
          = link_to new_discussion_path(parent_id: discussion.id), style: 'width:20px;border-radius:0', class: 'btn pull-right', title: 'комментировать', rel: 'tooltip', remote: true do
            %i.icon-comment        
      %div{id: "collapse#{discussion.id.to_s}", class: "accordion-body collapse #{'in' if index == -1}"}
        .accordion-inner
          = discussion.body
          .pull-right
            %small.muted= discussion.user_name            
          = render discussion.children if discussion.children
.modal.hide.fade

app/views/discussions/new.html.haml
%h1 New discussion

= render 'form'

= link_to 'Back', discussions_path

app/views/discussions/new.js.erb
$('.modal').html("<%= j render 'answer' %>");
$('.modal').modal();

app/views/discussions/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @discussion.title
%p
  %b Parent:
  = @discussion.parent_id
%p
  %b Visible:
  = @discussion.visible
%p
  %b Body:
  = @discussion.body
%p
  %b User:
  = @discussion.user_id
%p
  %b User name:
  = @discussion.user_name

= link_to 'Edit', edit_discussion_path(@discussion)
\|
= link_to 'Back', discussions_path