config/routes.rb
InitialRelease::Application.routes.draw do  
  
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :password_resets
  resources :sessions

  get 'wellcom' => 'home#wellcom'
  get 'set_city' => 'home#set_city', as: 'set_city'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  match '', to: 'cities#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  
  root :to =>  "cities#index", :requirements => { :subdomain => "voronezh" } #"cities#index"

  defaults :subdomain => false do
    root :to => 'cities#index'
  end

  resources :prices
  resources :promotions do
    post :search, on: :collection
    get :start    
  end

  resources :photo_prices
  resources :chains
  resources :products
  resources :discussions do
    member do
      get 'change_visible'
    end
  end

  resources :cities do
    get :set_shops_prices
    get :update_shop_raiting
    resources :shops
    resources :xml_files
    resource :shop_products
    resources :areas do
      resources :chains do 
        resources :shops
      end
    end
  end

  resources :areas do
    resources :shops
  end

  resources :users do
    resources :roles
    resources :xml_files
    member do
      get :activate
    end
    collection do 
      post :sign_with_social
    end
  end

  

end

app/models/user.rb
#encoding: utf-8
class User < ActiveRecord::Base
  rolify
  #establish_connection "production"  
  
  rolify :before_add => :before_add_method

  def before_add_method(role)
    # do something before it gets added
  end

  authenticates_with_sorcery!

  has_many :photo_prices
  has_many :shops, through: :user_shops
  has_many :user_shops
  belongs_to :city
  has_many :promotions
  has_many :discussions
  
  attr_accessible :email, :password, :password_confirmation, :city_id

  validates_confirmation_of :password, :on => :create
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  validate :check_city

  def check_city
    errors.add("city","Ошибочно указан город") if self.city_id && City.where(:id => self.city_id) == []
  end

  def to_s
  	self.email	
  end

  def admin?
    self.admin == true
  end

  def seller?
    self.has_role?(:seller, :any) || self.has_role?(:city, :any) || self.has_role?(:area, :any)
  end

  def chain
    Chain.find(roles.find_by_name('seller').resource_id)
  end

  def update_password(current_password, new_password, new_password_confirmation)
    if new_password == new_password_confirmation
      if !User.authenticate(self.email, current_password).nil?
        return self.change_password!(new_password)
      else
        return false
      end
    else
      return false
    end
  end

end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  before_filter :require_login, :except => [:new, :create, :activate, :sign_with_social]

  def index
    redirect_to new_user_path  
  end

  def new
    @user = User.new
  end

  def create
    if params[:token]
      logger.info('social auth start')
      token = params[:token]
      app_id = "30025"
      secret_key = "8374210538983a539635429893ff2584"
      if !token.nil?
        social_data = Loginza.user_data(params[:token], :options => {:id => app_id, :sig => secret_key})
        email = social_data['email']
        logger.info(email)
          if !email.nil?
          user = User.find_by_email(email)
          if(user.nil?)
            user = User.new(:email => email,
                            #:provider => social_data['provider'],
                            :first_name => social_data['name']['first_name'],
                            :last_name => social_data['name']['last_name'],
                            #:nickname => social_data['nickname'],
                            :authentication_token => social_data['uid'],
                            :password => secret_key)
            #user.skip_confirmation!
            user.save
            user.activate!
          end
        sign_in user, :bypass => true
       end       
      end
      redirect_to root_url#, :notice => "Вы успешно зарегистрировались на сайте"
    else
      @user = User.new(params[:user])
      if @user.save
        #отправка сообщения для активации
        UserMailer.activation_needed_email(@user).deliver        
        if params[:photo_price]
          @photo_price = PhotoPrice.find(params[:photo_price])
          @photo_price.update_attributes(user_id: @user.id) if @photo_price.user_id == nil
        end
        redirect_to root_url, :notice => "Вы успешно зарегистрировались на сайте"
      else
        render :new
      end
    end
  end

  def sign_with_social
    token = params[:token]  #достаем токен из запроса
    if !token.nil?
     
      #выполняем удаленный запрос на сайт ulogin
      require 'net/http'
      url = URI.parse('http://ulogin.ru/token.php?token='+token) 
      
      #парсим полученные данные
      social_data = ActiveSupport::JSON.decode(Net::HTTP.get(url))
      uid = social_data['identity']
      email = social_data['email']
      first_name = social_data['first_name']
      last_name = social_data['last_name']
      
      #Ищем пользователя по email
      @user = User.find_by_email(email)
      if @user.nil?
        
        #Если пользователь с email не найден, то ищем пользователя по по уникальному id    пользователя на социальном ресурсе
        @user = User.find_by_authentication_token(uid)
        my_time = Time.now
        
        #Если пользователь не найден, то создаем нового с параметрами как в соц сети
        if @user.nil?
          @user = User.new
          @user.email=email
          @user.password="password"
          @user.authentication_token=uid
          @user.first_name=first_name
          @user.last_name=last_name
          #@user.skip_confirmation! #необходим для того, чтобы сообщение о подтверждении авторизации не высылалось по email
          @user.save
          @user.activate!
        end
      end
      #авторизируем найденного или нового созданного пользователя в системе
      #sign_in @user, :bypass => true
      #login(@user.email, "password", true)
      auto_login(@user)
      current_user = @user
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
    @users = User.all if current_user && current_user.admin?
    redirect_to edit_user_path(current_user) if !current_user.admin? && @user != current_user
  end

  def update
    @user = User.find(params[:id])
    redirect_to edit_user_path(current_user) if !current_user.admin? && @user != current_user
    if params[:user] && (@user == current_user || current_user.admin?) 
      @user.email = params[:user][:email]
      @user.city_id = params[:user][:city_id]
      flash[:info] = "Данные обновлены"
      @user.save

      if params[:old_password] && !params[:old_password].blank? 
        if @user.update_password(params[:old_password], params[:user][:password], params[:user][:password_confirmation])
          flash[:info] = "Пароль успешно изменен"
        else
          flash[:info] = "Неверный пароль"
        end
      end
    end
    #render 'edit'
    #@user.update_attributes(params[:user]) #if @user == current_user || current_user.admin?
    redirect_to edit_user_path(@user)
  end

  def destroy
    User.find(params[:id]).destroy if current_user.admin?
    redirect_to edit_user_path(current_user)
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      current_user = @user      
      redirect_to edit_user_path(current_user) #(login_path, :notice => 'Активация прошла успешно')
    else
      not_authenticated
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
:javascript
  //function getFile(){ document.getElementById("upfile").click(); }
  $(document).ready(function() { 
    $('#add-price').click(function(){ $('#upfile').click(); });
    $('.chzn-chains').chosen();
    $('.chzn-select-deselect').chosen().change(function() {
      var id = $(this).val();
      $.get('/cities/'+id+'/areas.js', function(data){});
      //document.location.href="/cities/"+id; //http://sravnim-ka.ru
      //alert('sdf')
    });
    $('body').my_upload();    
  });
= form_for @user, html: {class:'form-horizontal'} do |f|
  .well.well-small  
    %legend Общая информация
    .control-group
      %label.control-label{:for => "inputEmail"} Email
      .controls
        = f.text_field :email, id:'inputEmail', placeholder:"Email", class: 'span8'      
    .control-group
      %label.control-label{:for => "inputCity"} Город
      .controls
        = select_tag "user[city_id]", options_from_collection_for_select(City.all, "id", "alias"), :prompt => @user.city_id != nil ? (@user.city == nil ? ' ' : @user.city.name) : 'выберите город', class: 'span8'    
        = f.submit 'сохранить', class:'btn pull-right'
  .well.well-small
    %legend Смена пароля
    .control-group
      %label.control-label{:for => "inputPasswordOld"} Старый пароль
      .controls
        = password_field_tag 'old_password', '', id:'inputPasswordOld', placeholder:"Старый пароль", class: 'span8'
    .control-group
      %label.control-label{:for => "inputPassword"} Новый пароль
      .controls
        = f.password_field :password, id:'inputPassword', placeholder:"Новый пароль", class: 'span8'
    .control-group
      %label.control-label{:for => "inputPasswordConfirm"} Пароль еще раз
      .controls
        = f.password_field :password_confirmation, id:'inputPasswordConfirm', placeholder:"Повторите пароль", class: 'span8'
        = f.submit 'сохранить', class:'btn pull-right'
- if current_user.admin?
  .well.well-small
    %legend 
      Пользователи и роли
    %table.table
      - @users.each do |user|
        %tr
          %td= user
          %td= user.chain.name if user.seller?
          %td= link_to 'изменить аккаунт', edit_user_path(user)
          %td= link_to 'удалить', user, method: 'delete', confirm: 'Вы уверены?'
          %td= link_to 'изменить роли', [user, :roles]
- if current_user.admin?
  .well.well-small
    %p
      = link_to 'продукты', products_path, class: 'btn btn-success'
      = link_to 'сети', chains_path, class: 'btn btn-success'
- if current_user.admin?
  .modal.hide.fade    
  %script    
    jQuery.fn.shop_choise = function(event, data){ 
    $('.chzn-shops').change(function() {
    var id = $(this).val();
    var city_id = $('.chzn-city').val();
    $.get('/cities/'+city_id+'/shops/'+id+'/edit.js', function(data){});
    });}
  .well.well-small
    %legend 
      Магазины и прайс-листы
      %small.pull-right= link_to 'скачать шаблон', '/price.xls'   
    .container
      .row
        .offset1.span4
          = image_tag('excel.png')
          %button#add-price.btn{onclick: "getFile();"} добавить прайс сети
          %script{id:"template-upload", type:"text/x-tmpl"}
            %div.upload.span2{style: 'display:block;position:relative;top:10px;left:10px;'}
        .span4
          = form_for [@user, XmlFile.new] do |f|  
            #shops 
              - if current_user.admin?
                .span6= select_tag("chain_id", options_from_collection_for_select(Chain.order('name'), 'id', 'name'), :include_blank => true, :'data-placeholder' =>  'выберите сеть', id: 'chain', class: 'select chzn-chains')
                %br/
                %br/    
              - elsif current_user.has_role? :seller, :any
                = hidden_field_tag 'chain_id', current_user.roles.find_by_name('seller').resource_id, id: 'chain'
              .span6= select_tag("city_id", options_from_collection_for_select(City.order('alias'), 'id', 'alias'), :include_blank => true, :'data-placeholder' => 'Выберите город', class: 'chzn-select-deselect chzn-city')
              .span6.area   
              %br/ 
              .span6.shop    
            %br/
            %br/
            .file-btn{style: 'position:absolute;left:-10000px;'}
              = f.file_field :attach, name: "xml_file[attach]", class: 'btn btn-mini new_xml_file', id: 'upfile'      
      %br/
      .row
        .span10
          .price{style:'clear:both'}           
/- if current_user && (current_user.admin? || current_user.seller?)
/  .well.well-small#shops
/    %legend Магазины и прайсы
/    - if current_user.seller?
/      %label
/        Сеть магазинов: 
/        = current_user.chain
/    .row
/      = form_for XmlFile.new(chain_id: current_user.chain.id), html: {style:"padding-top:10px;padding-left:70px;padding-right:90px;"} do |f|
/        .controlls 
/          = f.hidden_field :chain_id
/          %label.control-label{:for => "xml_file_attach", style: 'display:inline'} Добавить общий прайс сети:&nbsp;&nbsp;&nbsp;
/          = f.file_field :attach, name: "xml_file[attach]", class: 'btn btn-mini new_xml_file'
/        %script{id:"template-upload", type:"text/x-tmpl"}
/          %div.upload
/            {%=o.name%}
/            %div.progress
/              %div.bar{style:"width: 0%"}
/      .offset2.span4= select_tag("city[id]", options_from_collection_for_select(City.all, 'id', 'name'), prompt: 'выберите город', class: 'chzn-select-/deselect')
/      .span4.area  
/    %hr/
/    .new_form
/    .shops

app/views/users/new.html.haml
= form_for @user, html: {class:'form-horizontal'} do |f|
  %legend Регистрация
  - if @user.errors.any?  
    .error_messages
      %h3 Ошибка регистрации
      %ul
        - for message in @user.errors.full_messages
          %li= message
  .control-group
    = hidden_field_tag 'photo_price', params[:photo_price] if params[:photo_price]
    %label.control-label{:for => "inputEmail"} Email
    .controls
      = f.text_field :email, id:'inputEmail', placeholder:"Email", class: 'span6'
  .control-group
    %label.control-label{:for => "inputCity"} Город
    .controls
      = select_tag "user[city_id]", options_from_collection_for_select(City.all, "id", "alias"), :prompt => "выберите город", class: 'span6'
  .control-group
    %label.control-label{:for => "inputPassword"} Пароль
    .controls
      = f.password_field :password, id:'inputPassword', placeholder:"Пароль", class: 'span6'
  .control-group
    %label.control-label{:for => "inputPasswordConfirm"} Пароль еще раз
    .controls
      = f.password_field :password_confirmation, id:'inputPasswordConfirm', placeholder:"Повторите пароль", class: 'span6'     
  .control-group
    .controls
      = f.submit 'Зарегистрировать', class:'btn btn-primary btn-large span6'
%h5 
  Также Вы можете зайти на сайт используя социальные сети: 
  %script{src:"http://ulogin.ru/js/ulogin.js"}
  #uLogin{'x-ulogin-params'=>"display=panel;fields=first_name,last_name,email;providers=vkontakte,odnoklassniki,mailru,facebook;redirect_uri=http%3A%2F%2Fsravnim-ka.com:3000/users/sign_with_social", style: 'inline-block'}
  -#= loginza_button_tag(users_url, :provider => :google) do
  -#  .loginza
  -#    %img{src:"http://loginza.ru/img/providers/google.png", alt:"Google", title:"Google Accounts"}
  -#    %img{src:"http://loginza.ru/img/providers/twitter.png", alt:"Twitter", title:"Twitter"}
  -#    %img{src:"http://loginza.ru/img/providers/yandex.png", alt:"Yandex", title:"Yandex"}
  -#    %img{src:"http://loginza.ru/img/providers/myopenid.png", alt:"MyOpenID", title:"MyOpenID"}
  -#    %img{src:"http://loginza.ru/img/providers/openid.png", alt:"OpenID", title:"OpenID"}  