config/routes.rb
InitialRelease::Application.routes.draw do  
  
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :password_resets
  resources :sessions

  get 'wellcom' => 'home#wellcom'
  get 'set_city' => 'home#set_city', as: 'set_city'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  match '', to: 'cities#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  
  root :to =>  "cities#index", :requirements => { :subdomain => "voronezh" } #"cities#index"

  defaults :subdomain => false do
    root :to => 'cities#index'
  end

  resources :prices
  resources :promotions do
    post :search, on: :collection
    get :start    
  end

  resources :photo_prices
  resources :chains
  resources :products
  resources :discussions do
    member do
      get 'change_visible'
    end
  end

  resources :cities do
    get :set_shops_prices
    get :update_shop_raiting
    resources :shops
    resources :xml_files
    resource :shop_products
    resources :areas do
      resources :chains do 
        resources :shops
      end
    end
  end

  resources :areas do
    resources :shops
  end

  resources :users do
    resources :roles
    resources :xml_files
    member do
      get :activate
    end
    collection do 
      post :sign_with_social
    end
  end

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #skip_before_filter :require_login, :only => :wellcom

  def wellcom
    render 'wellcom'#, layout: false
  end

  def set_city    
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/city.html.haml
%legend Выберите город
%table{style: 'margin: 0 auto;'}
  - City.all.each_with_index do |city, index|
    != "<tr>" if (index+1)%3 == 1
    !=  "<td>" + (link_to city.name, {controller: 'cities', action: 'show', id: city.id}, class: 'btn btn-info btn-large', style: 'width:150px') + "</td>"
    != "</tr>" if (index+1)%3 == 0

app/views/home/set_city.js.erb
// Создание метки 
var myPlacemark3 = new ymaps.Placemark(
        // Координаты метки
        [51.659803804512855,39.2379025136719], {
            /* Свойства метки:
               - контент значка метки */
            iconContent: "рядом",
            // - контент балуна метки
            balloonContent: "парк Алые паруса"
        }, {
            /* Опции метки:
               - флаг перетаскивания метки */
            draggable: true,
            /* - показывать значок метки 
               при открытии балуна */
            hideIconOnBalloonOpen: true
        }
    );

// Добавление метки на карту
myMap.geoObjects.add(myPlacemark3);

app/views/home/wellcom.html.haml
%script{:src => "http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU", :type => "text/javascript"}
%script{:src => "http://yandex.st/jquery/1.6.4/jquery.min.js", :type => "text/javascript"}
:javascript
  ymaps.ready(init);
  var myMap, 
      myPlacemark;

  function init(){ 
      myMap = new ymaps.Map ("map", {
          center: [51.664768,39.178851],
          zoom: 12
      });           
      myPlacemark = new ymaps.Placemark([51.655413,39.244383], {
          content: 'мой дом',
          balloonContent: '<span style="color:red">мой дом</span><br />Ленинский пр-т, 82'
      });          
      myPlacemark2 = new ymaps.Placemark([51.663687,39.182563], {
          content: 'мой дом',
          balloonContent: '<span style="color:red">здесь работа</span><br />Свободы, 75'
      });                    
      
      myMap.geoObjects.add(myPlacemark);
      myMap.geoObjects.add(myPlacemark2);

      //зум
      myMap.controls.add('zoomControl');
      myMap.behaviors.enable('scrollZoom');
      //поиск
      myMap.controls.add('searchControl');
      
      /* При щелчке на карте показывается балун со значениями координат в месте клика */
      myMap.events.add("click",
          function(e) {
              myMap.balloon.open(
                  // Позиция балуна
                  e.get("coordPosition"), {
                      // Свойства балуна:
                      // контент балуна
                      contentBody: "Значение: " +
                      e.get("coordPosition")
                  }   
              )
          }
      );

      myPlacemark.events.add('click', function (e) {
        //alert('щелчок по объекту');
      });      
  }
#map{:style => "width: 600px; height: 400px"}
= link_to 'set', set_city_path, remote: true