config/routes.rb
InitialRelease::Application.routes.draw do  
  
  mount Ckeditor::Engine => '/ckeditor'
  
  resources :password_resets
  resources :sessions

  get 'wellcom' => 'home#wellcom'
  get 'set_city' => 'home#set_city', as: 'set_city'
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  match '', to: 'cities#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  
  root :to =>  "cities#index", :requirements => { :subdomain => "voronezh" } #"cities#index"

  defaults :subdomain => false do
    root :to => 'cities#index'
  end

  resources :prices
  resources :promotions do
    post :search, on: :collection
    get :start    
  end

  resources :photo_prices
  resources :chains
  resources :products
  resources :discussions do
    member do
      get 'change_visible'
    end
  end

  resources :cities do
    get :set_shops_prices
    get :update_shop_raiting
    resources :shops
    resources :xml_files
    resource :shop_products
    resources :areas do
      resources :chains do 
        resources :shops
      end
    end
  end

  resources :areas do
    resources :shops
  end

  resources :users do
    resources :roles
    resources :xml_files
    member do
      get :activate
    end
    collection do 
      post :sign_with_social
    end
  end

  

end

app/models/chain.rb
class Chain < ActiveRecord::Base
  #establish_connection "production"
  resourcify
  
	has_many :shops

  has_and_belongs_to_many :cities, :uniq => true
  has_and_belongs_to_many :areas, :uniq => true

	has_attached_file :logo, :styles => { :thumb=> ["140x140", :png] }, :whiny => false

   def to_s
    name
  end
end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
  skip_before_filter :require_login, :only => :wellcom
  before_filter :check_admin

  def check_admin
    if !current_user || !current_user.admin?
      redirect_to :root
    end
  end

  def index
    @chains = Chain.all
  end

  def edit
    @chain = Chain.find(params[:id])    
  end

  def update
    @chain = Chain.find(params[:id])    
    @chain.update_attributes(params[:chain])
    redirect_to chains_path
  end

  def create
    @chain = Chain.create(params[:chain])
    redirect_to chains_path
  end
  
  def show
    if params[:id] 
      @area = Area.find(params[:area_id]) if params[:area_id]
      @chain = Chain.find(params[:id]) || Chain.first
      render 'cities/show'
    else
      redirect_to cities_path(@city.id)
    end
  end

  def destroy
    Chain.find(params[:id]).destroy
    redirect_to chains_path
  end

end

app/views/chains/edit.html.haml
= link_to 'назад', chains_path
= form_for @chain do |f|
  = f.text_field :name, placeholder: 'название'
  = f.text_field :site, placeholder: 'сайт'
  = f.file_field :logo
  = f.submit 'сохранить', class: 'btn'

app/views/chains/index.html.haml
= form_for Chain.new do |f|
  %label новая сеть
  = f.text_field :name, placeholder: 'название'
  = f.text_field :site, placeholder: 'сайт'
  = f.file_field :logo
  = f.submit 'создать', class: 'btn'
%table.table
  - @chains.each do |chain|
    %tr
      %td= chain.name
      %td= image_tag chain.logo(:thumb)
      %td
        = link_to edit_chain_path(chain), class: 'btn btn-success btn-pop', style: 'width:20px;', title: 'редактировать' do
          %i.icon-edit.icon-white
      %td
        = link_to chain, method: 'delete', confirm: 'вы уверены?', class: 'btn btn-danger btn-pop', style: 'width:20px;', title: 'удалить сеть' do
          %i.icon-trash.icon-white

app/views/chains/show.html.haml
= @chain.cities.each do |city|
  = city.name